### ISSUE TITLE
File Path Misdirection

### ISSUE THREAD

**Issue by exdysa** [hiddenswitch/ComfyUI#16]
### Expected Behavior

I have selected a `TransformersLoader` node and opened its options, I expect to see a place to enter a Transformers model.

### Actual Behavior

![Screenshot 2024-07-21 195506](https://github.com/user-attachments/assets/b9eee038-5377-4868-b453-be497eeac93f)

Observe the field retrieval is not from a folder. I was not able to trace where it comes from, the folder structure `city96/SD-Latent-Interposer` does not appear to be on my system. Is it pulling from a file?

### Steps to Reproduce

Use `--disable-known-models` and load a `TransformersLoader` node. Voila, the conditions for calamity are met.

### Debug Logs

```powershell
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1
```

### Other
<img width="663" alt="Screen Shot 2024-07-21 at 20 08 18" src="https://github.com/user-attachments/assets/189465ec-693a-485e-b56f-5c0b60bc4dcf">

<img width="687" alt="Screen Shot 2024-07-21 at 19 53 53" src="https://github.com/user-attachments/assets/1f3e89e2-69db-49fb-98db-17b0e2845cd4">

why dis
what if i *like* toil? what if i have limited file space on my computer (this is extremely so)? what if i do not wish to download strange files from the internet with no notice of where or how or what is saved in which location?

![Screenshot 2024-07-21 210027](https://github.com/user-attachments/assets/c0192a43-0869-4438-ba85-a381df056200)

Also happens in diffusersloader.

<img width="706" alt="Screen Shot 2024-07-21 at 21 01 10" src="https://github.com/user-attachments/assets/ef738c79-7666-4647-a53f-007415863e42">

**Comment by doctorpangloss** [comment]
> Observe the field retrieval is not from a folder. I was not able to trace where it comes from, the folder structure city96/SD-Latent-Interposer does not appear to be on my system. Is it pulling from a file?

`city96/SD-Latent-Interposer` should be in your HuggingFace cache.

Any transformers models added to the `models/huggingface` directory should appear there. Those should be in the form

`repoowner/repoid` from huggingface.com, aka the result of `snapshot_download` or a git clone of a huggingface repo.

I will add some documentation. Ultimately this is poorly communicated because it is really clunky to make UI changes - the UI should just say where the model comes from.

**Comment by exdysa** [comment]
> `city96/SD-Latent-Interposer` should be in your HuggingFace cache.

Why would a custom node that does not require any models be in my huggingface cache?

> Any transformers models added to the models/huggingface directory should appear there. Those should be in the form repoowner/repoid from huggingface.com, aka the result of snapshot_download or a git clone of a huggingface repo.

I manually download my models. I place them in folders outside of .huggingface. I know it is not using the system as designed, but I do not like the delay of surprise downloads, or the frustration of a full hard disk drive. Should I then manually put transformers models inside models/huggingface? or keep them in the pre-specified extra_model_paths area where I have told it on launch to look?

**Comment by exdysa** [comment]
![Screenshot 2024-07-26 142933](https://github.com/user-attachments/assets/5191ea1a-7383-49dc-8b4b-89c3eb5ec905) hm. i still dont understand how this got here, unless the field populated from somewhere else?

**Comment by doctorpangloss** [comment]
it's a little complicated to explain, but it has nothing to do with the comfyui fork's behavior. there are numerous python packages that use huggingface's `hf_hub_download` or `snapshot_download` functions, which use a system-wide cache for storing data that gets downloaded.

**Comment by exdysa** [comment]
Got it. Thank you 🤍
